// <auto-generated />
using System;
using System.Collections.Generic;
using Axis.BusinessObjects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Axis.BusinessObjects.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessObjectsDbContext))]
    [Migration("20260813111821_StandardizeResourceMetadata")]
    partial class StandardizeResourceMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectChoiceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_field_definition_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("option_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_field_choice_options_business_o~1");

                    b.ToTable("business_object_definition_field_choice_options", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_display_name");

                    b.Property<string>("CreatedByKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("created_by_kind");

                    b.Property<Guid?>("CreatedBySubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_subject_id");

                    b.Property<string>("InstalledComponentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("installed_component_hash");

                    b.Property<string>("InstalledComponentKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("installed_component_key");

                    b.Property<long?>("InstalledLeaseEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("installed_lease_epoch");

                    b.Property<Guid?>("InstalledOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installed_operation_id");

                    b.Property<Guid?>("InstalledSolutionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("installed_solution_version_id");

                    b.Property<Guid?>("InstalledStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("installed_step_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<int?>("LatestPublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .HasComputedColumnSql("axis_unaccent(lower(coalesce(name, '') || ' ' || coalesce(object_key, '')))", true);

                    b.Property<string>("SearchTitle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_title")
                        .HasComputedColumnSql("axis_unaccent(lower(coalesce(name, '')))", true);

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', axis_unaccent(lower(coalesce(name, '') || ' ' || coalesce(object_key, ''))))", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_display_name");

                    b.Property<string>("UpdatedByKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("updated_by_kind");

                    b.Property<Guid?>("UpdatedBySubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_subject_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_business_object_definitions_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchTitle")
                        .HasDatabaseName("ix_business_object_definitions_search_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTitle"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_business_object_definitions_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("WorkspaceId", "InstalledComponentKey")
                        .IsUnique()
                        .HasFilter("installed_component_key IS NOT NULL");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("business_object_definitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_business_object_definitions_installed_provenance", "(installed_solution_version_id IS NULL AND installed_component_key IS NULL AND\n installed_component_hash IS NULL AND installed_operation_id IS NULL AND\n installed_step_id IS NULL AND installed_lease_epoch IS NULL)\nOR\n(installed_solution_version_id IS NOT NULL AND installed_component_key IS NOT NULL AND\n installed_component_hash IS NOT NULL AND installed_operation_id IS NOT NULL AND\n installed_step_id IS NOT NULL AND installed_lease_epoch > 0 AND\n installed_component_key ~ '^[a-z][a-z0-9_.:@-]{0,199}$' AND\n installed_component_hash ~ '^[0-9a-f]{64}$' AND\n installed_solution_version_id <> '00000000-0000-0000-0000-000000000000'::uuid AND\n installed_operation_id <> '00000000-0000-0000-0000-000000000000'::uuid AND\n installed_step_id <> '00000000-0000-0000-0000-000000000000'::uuid)");
                        });
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_definition_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PublishedBySubject", "Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion.PublishedBySubject#SubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("published_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("published_by_subject_kind");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SourceDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Key", "VersionNumber")
                        .IsUnique();

                    b.ToTable("business_object_definition_versions", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionChoiceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionVersionFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_field_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("option_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceChoiceOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_choice_option_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_choice_options_bu~1");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "SourceChoiceOptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_choice_options_bu~2");

                    b.ToTable("business_object_definition_version_field_choice_options", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_id");

                    b.Property<string>("ChoiceSelectionMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("choice_selection_mode");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_field_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_version_fields_business_object_~1");

                    b.HasIndex("BusinessObjectDefinitionVersionId", "SourceFieldDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_fields_business_object_~2");

                    b.ToTable("business_object_definition_version_fields", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("binding_id");

                    b.Property<string>("BindingKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("installed_binding_key");

                    b.Property<int>("BindingRevision")
                        .HasColumnType("integer")
                        .HasColumnName("binding_revision");

                    b.Property<Guid>("BusinessObjectDefinitionVersionFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_field_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceFieldRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_field_rule_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "BindingId")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Order")
                        .HasDatabaseName("IX_business_object_definition_version_field_rules_business_ob~1");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "SourceFieldRuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_rules_business_ob~2");

                    b.ToTable("business_object_definition_version_field_rules", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_id");

                    b.Property<string>("ChoiceSelectionMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("choice_selection_mode");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_fields_business_object_definiti~1");

                    b.ToTable("business_object_definition_fields", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("binding_id");

                    b.Property<string>("BindingKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("installed_binding_key");

                    b.Property<int>("BindingRevision")
                        .HasColumnType("integer")
                        .HasColumnName("binding_revision");

                    b.Property<Guid>("BusinessObjectFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_field_definition_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectFieldDefinitionId", "BindingId")
                        .IsUnique();

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_field_rules_business_object_fie~1");

                    b.ToTable("business_object_definition_field_rules", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_version_id");

                    b.Property<int>("DefinitionVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version_number");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBySubject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("submitted_by_subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("_ruleEvaluations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_evaluations");

                    b.Property<string>("_values")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CreatedBySubject", "Axis.BusinessObjects.Domain.Aggregates.BusinessObjectRecord.CreatedBySubject#SubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("created_by_subject_kind");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Owner", "Axis.BusinessObjects.Domain.Aggregates.BusinessObjectRecord.Owner#SubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("owner_kind");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UpdatedBySubject", "Axis.BusinessObjects.Domain.Aggregates.BusinessObjectRecord.UpdatedBySubject#SubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("updated_by_subject_kind");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "DefinitionVersionId");

                    b.HasIndex("WorkspaceId", "ObjectKey", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ObjectKey", "UpdatedAt");

                    b.ToTable("business_object_records", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectChoiceOption", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", null)
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("BusinessObjectFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("SourceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionChoiceOption", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", null)
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("BusinessObjectDefinitionVersionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("BusinessObjectDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionFieldRule", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", null)
                        .WithMany("Rules")
                        .HasForeignKey("BusinessObjectDefinitionVersionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("BusinessObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldRule", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", null)
                        .WithMany("Rules")
                        .HasForeignKey("BusinessObjectFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.Navigation("ChoiceOptions");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.Navigation("ChoiceOptions");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
