// <auto-generated />
using System;
using Axis.BusinessObjects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axis.BusinessObjects.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessObjectsDbContext))]
    partial class BusinessObjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectChoiceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_field_definition_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("option_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_field_choice_options_business_o~1");

                    b.ToTable("business_object_definition_field_choice_options", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<int?>("LatestPublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("business_object_definitions", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<Guid>("SourceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_definition_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Key", "VersionNumber")
                        .IsUnique();

                    b.ToTable("business_object_definition_versions", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionChoiceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionVersionFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_field_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("option_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceChoiceOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_choice_option_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_choice_options_bu~1");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "SourceChoiceOptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_choice_options_bu~2");

                    b.ToTable("business_object_definition_version_field_choice_options", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_id");

                    b.Property<string>("ChoiceSelectionMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("choice_selection_mode");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_field_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_version_fields_business_object_~1");

                    b.HasIndex("BusinessObjectDefinitionVersionId", "SourceFieldDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_fields_business_object_~2");

                    b.ToTable("business_object_definition_version_fields", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionVersionFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_version_field_id");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("definition_key");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SourceFieldRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_field_rule_id");

                    b.Property<string>("_parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "DefinitionKey")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "Order")
                        .HasDatabaseName("IX_business_object_definition_version_field_rules_business_ob~1");

                    b.HasIndex("BusinessObjectDefinitionVersionFieldId", "SourceFieldRuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_business_object_definition_version_field_rules_business_ob~2");

                    b.ToTable("business_object_definition_version_field_rules", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_definition_id");

                    b.Property<string>("ChoiceSelectionMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("choice_selection_mode");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("BusinessObjectDefinitionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_fields_business_object_definiti~1");

                    b.ToTable("business_object_definition_fields", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessObjectFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_object_field_definition_id");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("definition_key");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("_parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectFieldDefinitionId", "DefinitionKey")
                        .IsUnique();

                    b.HasIndex("BusinessObjectFieldDefinitionId", "Order")
                        .HasDatabaseName("IX_business_object_definition_field_rules_business_object_fie~1");

                    b.ToTable("business_object_definition_field_rules", (string)null);
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectChoiceOption", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", null)
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("BusinessObjectFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("SourceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionChoiceOption", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", null)
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("BusinessObjectDefinitionVersionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("BusinessObjectDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionFieldRule", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", null)
                        .WithMany("Rules")
                        .HasForeignKey("BusinessObjectDefinitionVersionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("BusinessObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldRule", b =>
                {
                    b.HasOne("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", null)
                        .WithMany("Rules")
                        .HasForeignKey("BusinessObjectFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectDefinitionVersionField", b =>
                {
                    b.Navigation("ChoiceOptions");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Axis.BusinessObjects.Domain.Aggregates.BusinessObjectFieldDefinition", b =>
                {
                    b.Navigation("ChoiceOptions");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
