// <auto-generated />
using System;
using System.Collections.Generic;
using Axis.Rules.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Axis.Rules.Infrastructure.Migrations
{
    [DbContext(typeof(RulesDbContext))]
    [Migration("20260807072804_AddRuleSubjects")]
    partial class AddRuleSubjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.Rules.Domain.RuleBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("definition_key");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FailureBehavior")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("failure_behavior");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UseCaseOrTrigger")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("use_case_or_trigger");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("_inputMappings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_mappings");

                    b.Property<string>("_revisionHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("revision_history");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CreatedBySubject", "Axis.Rules.Domain.RuleBinding.CreatedBySubject#RuleSubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("created_by_subject_kind");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UpdatedBySubject", "Axis.Rules.Domain.RuleBinding.UpdatedBySubject#RuleSubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("updated_by_subject_kind");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "DefinitionKey", "DefinitionVersion");

                    b.HasIndex("WorkspaceId", "TargetType", "TargetId", "UseCaseOrTrigger", "DefinitionKey", "DefinitionVersion");

                    b.ToTable("rule_bindings", (string)null);
                });

            modelBuilder.Entity("Axis.Rules.Domain.RuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveVersion")
                        .HasColumnType("integer")
                        .HasColumnName("active_version");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("ArchivedBySubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("archived_by_subject_id");

                    b.Property<string>("ArchivedBySubjectKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("archived_by_subject_kind");

                    b.Property<string>("Condition")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("ExpressionLanguageVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expression_language_version");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("definition_key");

                    b.Property<int?>("LatestPublishedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .HasComputedColumnSql("axis_unaccent(lower(coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(definition_key, '')))", true);

                    b.Property<string>("SearchTitle")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_title")
                        .HasComputedColumnSql("axis_unaccent(lower(coalesce(name, '')))", true);

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', axis_unaccent(lower(coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(definition_key, ''))))", true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("_inputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inputs");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CreatedBySubject", "Axis.Rules.Domain.RuleDefinition.CreatedBySubject#RuleSubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("created_by_subject_kind");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UpdatedBySubject", "Axis.Rules.Domain.RuleDefinition.UpdatedBySubject#RuleSubjectReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by_subject_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("updated_by_subject_kind");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_rule_definitions_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchTitle")
                        .HasDatabaseName("ix_rule_definitions_search_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTitle"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_rule_definitions_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ArchivedAt", "ActiveVersion", "LatestPublishedVersion", "Name");

                    b.ToTable("rule_definitions", (string)null);
                });

            modelBuilder.Entity("Axis.Rules.Domain.RuleDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_definition_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("ExpressionLanguageVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expression_language_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedBySubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_subject_id");

                    b.Property<string>("PublishedBySubjectKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("published_by_subject_kind");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<string>("_inputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inputs");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("rule_definition_versions", (string)null);
                });

            modelBuilder.Entity("Axis.Rules.Domain.RuleDefinitionVersion", b =>
                {
                    b.HasOne("Axis.Rules.Domain.RuleDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Rules.Domain.RuleDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
