// <auto-generated />
using System;
using Axis.Objects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axis.Objects.Infrastructure.Migrations
{
    [DbContext(typeof(ObjectsDbContext))]
    [Migration("20260708155858_AddFieldVariants")]
    partial class AddFieldVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<int?>("LatestPublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("object_definitions", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Key", "VersionNumber")
                        .IsUnique();

                    b.ToTable("object_definition_versions", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ObjectDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_version_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionVersionId", "Key")
                        .IsUnique();

                    b.HasIndex("ObjectDefinitionVersionId", "Order")
                        .HasDatabaseName("IX_object_definition_version_fields_object_definition_version~1");

                    b.ToTable("object_definition_version_fields", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionFieldVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("MaxDate")
                        .HasColumnType("date")
                        .HasColumnName("max_date");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<decimal?>("MaxNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_number");

                    b.Property<DateOnly?>("MinDate")
                        .HasColumnType("date")
                        .HasColumnName("min_date");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<decimal?>("MinNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_number");

                    b.Property<Guid>("ObjectDefinitionVersionFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_version_field_id");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Pattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pattern");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionVersionFieldId", "Kind")
                        .IsUnique();

                    b.HasIndex("ObjectDefinitionVersionFieldId", "Order")
                        .HasDatabaseName("IX_object_definition_version_field_variants_object_definition~1");

                    b.ToTable("object_definition_version_field_variants", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("ObjectDefinitionId", "Order");

                    b.ToTable("object_definition_fields", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("MaxDate")
                        .HasColumnType("date")
                        .HasColumnName("max_date");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<decimal?>("MaxNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_number");

                    b.Property<DateOnly?>("MinDate")
                        .HasColumnType("date")
                        .HasColumnName("min_date");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<decimal?>("MinNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_number");

                    b.Property<Guid>("ObjectFieldDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_field_definition_id");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Pattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pattern");

                    b.HasKey("Id");

                    b.HasIndex("ObjectFieldDefinitionId", "Kind")
                        .IsUnique();

                    b.HasIndex("ObjectFieldDefinitionId", "Order")
                        .HasDatabaseName("IX_object_definition_field_variants_object_field_definition_i~1");

                    b.ToTable("object_definition_field_variants", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("ObjectDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionFieldVariant", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", null)
                        .WithMany("Variants")
                        .HasForeignKey("ObjectDefinitionVersionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldVariant", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", null)
                        .WithMany("Variants")
                        .HasForeignKey("ObjectFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
