// <auto-generated />
using System;
using Axis.Objects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axis.Objects.Infrastructure.Migrations
{
    [DbContext(typeof(ObjectsDbContext))]
    [Migration("20260707114839_InitialObjects")]
    partial class InitialObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer")
                        .HasColumnName("draft_version");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<int?>("LatestPublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_published_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("object_definitions", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("object_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Key", "VersionNumber")
                        .IsUnique();

                    b.ToTable("object_definition_versions", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ObjectDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_version_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionVersionId", "Key")
                        .IsUnique();

                    b.HasIndex("ObjectDefinitionVersionId", "Order")
                        .HasDatabaseName("IX_object_definition_version_fields_object_definition_version~1");

                    b.ToTable("object_definition_version_fields", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("field_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ObjectDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_definition_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ObjectDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("ObjectDefinitionId", "Order");

                    b.ToTable("object_definition_fields", (string)null);
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersionField", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("ObjectDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectFieldDefinition", b =>
                {
                    b.HasOne("Axis.Objects.Domain.Aggregates.ObjectDefinition", null)
                        .WithMany("Fields")
                        .HasForeignKey("ObjectDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Axis.Objects.Domain.Aggregates.ObjectDefinitionVersion", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
