<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Authorization\Axis.Authorization.Contracts\Axis.Authorization.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Identity\Axis.Identity.Contracts\Axis.Identity.Contracts.csproj" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\BusinessObjects\Axis.BusinessObjects.Application\Axis.BusinessObjects.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\BusinessObjects\Axis.BusinessObjects.Contracts\Axis.BusinessObjects.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Rules\Axis.Rules.Application\Axis.Rules.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Rules\Axis.Rules.Contracts\Axis.Rules.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\Axis.Testing\Axis.Testing.csproj" />
  </ItemGroup>

</Project>
