export type AxisPrimitiveReadiness = 'ready' | 'candidate';

export type AxisPrimitiveTokenFamily =
  | 'border'
  | 'breakpoint'
  | 'color'
  | 'motion'
  | 'radius'
  | 'shadow'
  | 'sizing'
  | 'spacing'
  | 'typography';

export interface AxisPrimitiveContract {
  component: string;
  file: string;
  testFiles: readonly string[];
  readiness: AxisPrimitiveReadiness;
  variants: readonly string[];
  states: readonly string[];
  accessibility: readonly string[];
  tokenFamilies: readonly AxisPrimitiveTokenFamily[];
}

export const axisPrimitiveContracts = [
  {
    component: 'ActionLink',
    file: 'frontend/src/components/ui/action-link.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['primary', 'secondary', 'surface-default', 'surface-inverted', 'surface-adaptive'],
    states: ['default'],
    accessibility: ['router-link', 'decorative-icon', 'text-accessible-name'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'spacing'],
  },
  {
    component: 'Badge',
    file: 'frontend/src/components/ui/badge.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: [
      'neutral',
      'primary',
      'accent',
      'info',
      'success',
      'warning',
      'destructive',
      'outline',
    ],
    states: ['default'],
    accessibility: ['text-accessible-name', 'non-color-state-label'],
    tokenFamilies: ['color', 'border', 'radius'],
  },
  {
    component: 'Button',
    file: 'frontend/src/components/ui/button.tsx',
    testFiles: ['frontend/tests/button.test.tsx'],
    readiness: 'ready',
    variants: [
      'cta',
      'default',
      'outline',
      'secondary',
      'ghost',
      'destructive',
      'link',
      'size-xs',
      'size-sm',
      'size-default',
      'size-lg',
    ],
    states: ['default', 'disabled', 'loading', 'invalid'],
    accessibility: ['native-button', 'aria-busy-loading', 'disabled-interaction', 'icon-required'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'sizing', 'motion'],
  },
  {
    component: 'Card',
    file: 'frontend/src/components/ui/card.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['surface-default', 'header', 'content', 'footer'],
    states: ['default'],
    accessibility: ['semantic-caller-owned', 'heading-content-order'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'spacing'],
  },
  {
    component: 'Checkbox',
    file: 'frontend/src/components/ui/checkbox.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['unchecked', 'checked'],
    states: ['default', 'checked', 'disabled', 'invalid'],
    accessibility: ['native-checkbox', 'focus-visible', 'aria-invalid'],
    tokenFamilies: ['color', 'border', 'radius'],
  },
  {
    component: 'CheckboxField',
    file: 'frontend/src/components/ui/checkbox-field.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['labelled', 'error'],
    states: ['checked', 'error', 'disabled'],
    accessibility: ['label-linked', 'aria-describedby-error', 'aria-invalid-error'],
    tokenFamilies: ['color', 'spacing'],
  },
  {
    component: 'ContentGrid',
    file: 'frontend/src/components/ui/content-grid.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['one-column', 'two-column', 'three-column'],
    states: ['responsive'],
    accessibility: ['semantic-caller-owned', 'reading-order-preserved'],
    tokenFamilies: ['spacing', 'breakpoint'],
  },
  {
    component: 'EmptyState',
    file: 'frontend/src/components/ui/empty-state.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['with-action', 'without-action'],
    states: ['empty'],
    accessibility: ['decorative-icon', 'heading-first', 'action-accessible'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'spacing'],
  },
  {
    component: 'FormField',
    file: 'frontend/src/components/ui/form-field.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['label', 'help-text', 'error', 'description-ids'],
    states: ['default', 'error'],
    accessibility: ['label-linked', 'aria-describedby', 'error-id'],
    tokenFamilies: ['color', 'spacing'],
  },
  {
    component: 'IconButton',
    file: 'frontend/src/components/ui/icon-button.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['outline', 'secondary', 'destructive', 'size-icon', 'size-icon-sm', 'size-icon-lg'],
    states: ['default', 'disabled', 'loading'],
    accessibility: ['aria-label-required', 'loading-label', 'decorative-icon'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'sizing'],
  },
  {
    component: 'Input',
    file: 'frontend/src/components/ui/input.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['text', 'with-leading-icon'],
    states: ['default', 'disabled', 'invalid', 'described'],
    accessibility: ['label-or-aria-label', 'aria-invalid', 'aria-describedby'],
    tokenFamilies: ['color', 'border', 'radius', 'sizing'],
  },
  {
    component: 'Label',
    file: 'frontend/src/components/ui/label.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['default', 'normal-weight'],
    states: ['default'],
    accessibility: ['html-for-control', 'compact-label'],
    tokenFamilies: ['color', 'typography'],
  },
  {
    component: 'Notice',
    file: 'frontend/src/components/ui/notice.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['info', 'success', 'warning', 'error'],
    states: ['status', 'alert'],
    accessibility: ['role-status', 'role-alert', 'decorative-icon', 'non-color-state-copy'],
    tokenFamilies: ['color', 'border', 'radius', 'spacing'],
  },
  {
    component: 'PageHeader',
    file: 'frontend/src/components/ui/page-header.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['with-eyebrow', 'with-description', 'with-actions'],
    states: ['responsive'],
    accessibility: ['heading-order', 'actions-after-title'],
    tokenFamilies: ['color', 'typography', 'spacing', 'breakpoint'],
  },
  {
    component: 'Panel',
    file: 'frontend/src/components/ui/panel.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['default', 'muted', 'inset', 'attention', 'inverse'],
    states: ['default'],
    accessibility: ['semantic-caller-owned', 'focusable-content-visible'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'spacing'],
  },
  {
    component: 'Progress',
    file: 'frontend/src/components/ui/progress.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['determinate', 'indeterminate'],
    states: ['in-progress', 'complete'],
    accessibility: ['accessible-label', 'native-progress'],
    tokenFamilies: ['color', 'radius', 'sizing'],
  },
  {
    component: 'Select',
    file: 'frontend/src/components/ui/select.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['native-select'],
    states: ['default', 'disabled', 'invalid', 'described'],
    accessibility: ['label-or-aria-label', 'aria-invalid', 'aria-describedby'],
    tokenFamilies: ['color', 'border', 'radius', 'sizing'],
  },
  {
    component: 'Skeleton',
    file: 'frontend/src/components/ui/skeleton.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['line', 'block'],
    states: ['loading'],
    accessibility: ['aria-hidden', 'layout-stable'],
    tokenFamilies: ['color', 'radius', 'motion'],
  },
  {
    component: 'Textarea',
    file: 'frontend/src/components/ui/textarea.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['long-text', 'resizable'],
    states: ['default', 'disabled', 'invalid', 'described'],
    accessibility: ['label-or-aria-label', 'aria-invalid', 'aria-describedby'],
    tokenFamilies: ['color', 'border', 'radius', 'sizing'],
  },
  {
    component: 'Toolbar',
    file: 'frontend/src/components/ui/toolbar.tsx',
    testFiles: ['frontend/tests/ui-primitives.test.tsx'],
    readiness: 'ready',
    variants: ['text-actions', 'icon-actions', 'wrapping'],
    states: ['responsive'],
    accessibility: ['action-order-preserved', 'keyboard-reachable'],
    tokenFamilies: ['color', 'border', 'shadow', 'radius', 'spacing'],
  },
] as const satisfies readonly AxisPrimitiveContract[];
