<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axis.Core\Axis.Core.csproj" />
    <ProjectReference Include="..\Axis.Data\Axis.Data.csproj" />
    <ProjectReference Include="..\Axis.Tenancy\Axis.Tenancy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Axis.Integration.Tests" />
  </ItemGroup>

</Project>
