# generate-diagrams.ps1
# Regenerates all SVG images from .excalidraw source files using Kroki.io.
# Recursively scans docs/diagrams/ and docs/epics/*/diagrams/ for .excalidraw files.
#
# Usage:                  .\docs\scripts\generate-diagrams.ps1
# Usage (single file):    .\docs\scripts\generate-diagrams.ps1 -Filter "auth-flow"
#
# Source files: regenerated by:  node docs/diagrams/generate-diagrams.mjs
# Kroki endpoint: https://kroki.io/excalidraw/svg  (POST, body = raw JSON)

param(
    [string]$Filter = ""
)

function Export-ExcalidrawToSvg {
    param([string]$SourcePath, [string]$SvgPath)

    $content = Get-Content $SourcePath -Raw -Encoding UTF8
    $body    = [System.Text.Encoding]::UTF8.GetBytes($content)

    try {
        Invoke-WebRequest `
            -Uri         "https://kroki.io/excalidraw/svg" `
            -Method      POST `
            -Body        $body `
            -ContentType "text/plain; charset=utf-8" `
            -TimeoutSec  30 `
            -OutFile     $SvgPath
        $size = [math]::Round((Get-Item $SvgPath).Length / 1024, 1)
        Write-Host "  OK  ($size KB) $([System.IO.Path]::GetFileName($SvgPath))" -ForegroundColor Green
    } catch {
        Write-Host "  FAIL $([System.IO.Path]::GetFileName($SourcePath)): $_" -ForegroundColor Red
    }
}

$docsRoot = Split-Path $PSScriptRoot -Parent

# Collect all .excalidraw files from docs/diagrams/ and docs/epics/*/diagrams/
$searchPaths = @(
    "$docsRoot\diagrams",
    "$docsRoot\epics\E01-platform-foundation\diagrams",
    "$docsRoot\epics\E02-identity-access\diagrams",
    "$docsRoot\epics\E03-data-modeling\diagrams",
    "$docsRoot\epics\E04-workflow-builder\diagrams",
    "$docsRoot\epics\E05-form-builder\diagrams",
    "$docsRoot\epics\E06-workflow-engine\diagrams"
)

$files = foreach ($dir in $searchPaths) {
    if (Test-Path $dir) {
        Get-ChildItem -Path $dir -Filter "*.excalidraw" -File
    }
}

if ($Filter) {
    $files = $files | Where-Object { $_.Name -like "*$Filter*" }
}

Write-Host ""
Write-Host "Generating $($files.Count) SVG(s) from .excalidraw via Kroki.io..." -ForegroundColor Cyan
Write-Host ""

foreach ($f in $files) {
    $svgPath = [System.IO.Path]::ChangeExtension($f.FullName, ".svg")
    Export-ExcalidrawToSvg -SourcePath $f.FullName -SvgPath $svgPath
    Start-Sleep -Milliseconds 300
}

Write-Host ""
Write-Host "Done. Commit both .excalidraw and .svg files." -ForegroundColor Cyan
