# generate-diagrams.ps1
# Regenerates all SVG images from .excalidraw source files using Kroki.io.
# Recursively scans docs/architecture/diagrams/ and docs/use-cases/*/* for .excalidraw diagram sources.
#
# Usage:                  .\docs\scripts\generate-diagrams.ps1
# Usage (single file):    .\docs\scripts\generate-diagrams.ps1 -Filter "auth-flow"
#
# Source files: regenerated by:  node docs/architecture/generate-diagrams.mjs
# Kroki endpoint: https://kroki.io/excalidraw/svg  (POST, body = raw JSON)

param(
    [string]$Filter = ""
)

function Export-ExcalidrawToSvg {
    param([string]$SourcePath, [string]$SvgPath)

    $content = Get-Content $SourcePath -Raw -Encoding UTF8
    $body    = [System.Text.Encoding]::UTF8.GetBytes($content)

    try {
        Invoke-WebRequest `
            -Uri         "https://kroki.io/excalidraw/svg" `
            -Method      POST `
            -Body        $body `
            -ContentType "text/plain; charset=utf-8" `
            -TimeoutSec  30 `
            -OutFile     $SvgPath
        $size = [math]::Round((Get-Item $SvgPath).Length / 1024, 1)
        Write-Host "  OK  ($size KB) $([System.IO.Path]::GetFileName($SvgPath))" -ForegroundColor Green
    } catch {
        Write-Host "  FAIL $([System.IO.Path]::GetFileName($SourcePath)): $_" -ForegroundColor Red
    }
}

$docsRoot = Split-Path $PSScriptRoot -Parent

# Collect all .excalidraw files from docs/architecture/diagrams/ and docs/use-cases/*/* (use-case folders)
$searchPaths = @("$docsRoot\architecture\diagrams")
$useCasesRoot = Join-Path $docsRoot "use-cases"
if (Test-Path $useCasesRoot) {
    $searchPaths += Get-ChildItem -Path $useCasesRoot -Directory |
        Where-Object { $_.Name -notlike "_*" } |
        ForEach-Object {
            Get-ChildItem -Path $_.FullName -Directory |
                ForEach-Object { $_.FullName }
        }
}

$files = foreach ($dir in $searchPaths) {
    if (Test-Path $dir) {
        Get-ChildItem -Path $dir -Filter "*.excalidraw" -File
    }
}

if ($Filter) {
    $files = $files | Where-Object { $_.Name -like "*$Filter*" }
}

Write-Host ""
Write-Host "Generating $($files.Count) diagram(s) via Kroki.io..." -ForegroundColor Cyan
Write-Host ""

foreach ($file in $files) {
    $svgPath = [System.IO.Path]::ChangeExtension($file.FullName, ".svg")
    Export-ExcalidrawToSvg -SourcePath $file.FullName -SvgPath $svgPath
    Start-Sleep -Milliseconds 300
}

Write-Host ""
Write-Host "Done." -ForegroundColor Cyan
