// <auto-generated />
using System;
using Axis.Solutions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axis.Solutions.Infrastructure.Migrations
{
    [DbContext(typeof(SolutionsDbContext))]
    [Migration("20260808032751_InitialSolutions")]
    partial class InitialSolutions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("compliance_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProvisioningStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provisioning_status");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("SolutionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_version_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SolutionVersionId");

                    b.HasIndex("WorkspaceId", "SolutionVersionId")
                        .IsUnique();

                    b.ToTable("solution_installations", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorCorrelationId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_correlation_id");

                    b.Property<Guid>("ActorSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_subject_id");

                    b.Property<string>("ActorSubjectKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_subject_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<long>("LeaseEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_epoch");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("ProblemCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("problem_code");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("WorkspaceId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("solution_installation_operations", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ApplyingEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("applying_epoch");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component_key");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<string>("ProblemCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("problem_code");

                    b.Property<long?>("ReclaimedEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("reclaimed_epoch");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("component_sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("component_type");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Order")
                        .IsUnique();

                    b.ToTable("solution_installation_steps", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AxisOpenApiSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("axis_openapi_sha256");

                    b.Property<string>("BuildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("build_id");

                    b.Property<DateTimeOffset>("BuiltAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("built_at");

                    b.Property<byte[]>("Envelope")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("envelope");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("package_sha256");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("publisher_id");

                    b.Property<string>("PublisherKeyId")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("publisher_key_id");

                    b.Property<string>("SolutionKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("solution_key");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_revision");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_uri");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SolutionKey", "Version")
                        .IsUnique();

                    b.HasIndex("SolutionKey", "Version", "PackageSha256")
                        .IsUnique();

                    b.ToTable("solution_versions", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Domain.TrustedPublisherKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConfigurationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("configuration_revision");

                    b.Property<bool>("IsTombstone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tombstone");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key_id");

                    b.Property<string>("PublicKeyPem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_pem");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("publisher_id");

                    b.Property<string>("SpkiSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spki_sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId", "KeyId")
                        .IsUnique();

                    b.ToTable("trusted_publisher_keys", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Infrastructure.Persistence.Entities.SolutionComponentRecord", b =>
                {
                    b.Property<Guid>("SolutionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_version_id");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("component_type");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component_key");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("DependsOnJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("depends_on");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("component_sha256");

                    b.HasKey("SolutionVersionId", "Type", "Key");

                    b.ToTable("solution_components", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Infrastructure.Persistence.Entities.SolutionsAuditOutboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_kind");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("OriginatingSubjectKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("originating_subject_kind");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ProblemCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("problem_code");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid?>("SolutionVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("EventId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("solutions_audit_outbox", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Infrastructure.Persistence.Entities.TrustedPublisherLedgerStateRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("ActiveRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("active_revision");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("trusted_publisher_ledger_state", (string)null);
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallation", b =>
                {
                    b.HasOne("Axis.Solutions.Domain.SolutionVersion", null)
                        .WithMany()
                        .HasForeignKey("SolutionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallationOperation", b =>
                {
                    b.HasOne("Axis.Solutions.Domain.SolutionInstallation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallationStep", b =>
                {
                    b.HasOne("Axis.Solutions.Domain.SolutionInstallationOperation", null)
                        .WithMany("Steps")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Solutions.Infrastructure.Persistence.Entities.SolutionComponentRecord", b =>
                {
                    b.HasOne("Axis.Solutions.Domain.SolutionVersion", null)
                        .WithMany()
                        .HasForeignKey("SolutionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Axis.Solutions.Domain.SolutionInstallationOperation", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
