/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'

const RegisterLazyRouteImport = createFileRoute('/register')()
const ProvisioningLazyRouteImport = createFileRoute('/provisioning')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgot-password')()
const CallbackLazyRouteImport = createFileRoute('/callback')()
const IndexLazyRouteImport = createFileRoute('/')()
const RegisterConfirmationLazyRouteImport = createFileRoute(
  '/register_/confirmation',
)()
const AuthVerifyLazyRouteImport = createFileRoute('/auth/verify')()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const ProvisioningLazyRoute = ProvisioningLazyRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/provisioning.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const CallbackLazyRoute = CallbackLazyRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/callback.lazy').then((d) => d.Route))
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RegisterConfirmationLazyRoute =
  RegisterConfirmationLazyRouteImport.update({
    id: '/register_/confirmation',
    path: '/register/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/register_.confirmation.lazy').then((d) => d.Route),
  )
const AuthVerifyLazyRoute = AuthVerifyLazyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/verify.lazy').then((d) => d.Route))
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/callback': typeof CallbackLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/provisioning': typeof ProvisioningLazyRoute
  '/register': typeof RegisterLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/auth/verify': typeof AuthVerifyLazyRoute
  '/register/confirmation': typeof RegisterConfirmationLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/callback': typeof CallbackLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/provisioning': typeof ProvisioningLazyRoute
  '/register': typeof RegisterLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/auth/verify': typeof AuthVerifyLazyRoute
  '/register/confirmation': typeof RegisterConfirmationLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/provisioning': typeof ProvisioningLazyRoute
  '/register': typeof RegisterLazyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/auth/verify': typeof AuthVerifyLazyRoute
  '/register_/confirmation': typeof RegisterConfirmationLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/provisioning'
    | '/register'
    | '/dashboard'
    | '/auth/verify'
    | '/register/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/provisioning'
    | '/register'
    | '/dashboard'
    | '/auth/verify'
    | '/register/confirmation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/provisioning'
    | '/register'
    | '/_authenticated/dashboard'
    | '/auth/verify'
    | '/register_/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackLazyRoute: typeof CallbackLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProvisioningLazyRoute: typeof ProvisioningLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  AuthVerifyLazyRoute: typeof AuthVerifyLazyRoute
  RegisterConfirmationLazyRoute: typeof RegisterConfirmationLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning': {
      id: '/provisioning'
      path: '/provisioning'
      fullPath: '/provisioning'
      preLoaderRoute: typeof ProvisioningLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register_/confirmation': {
      id: '/register_/confirmation'
      path: '/register/confirmation'
      fullPath: '/register/confirmation'
      preLoaderRoute: typeof RegisterConfirmationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackLazyRoute: CallbackLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProvisioningLazyRoute: ProvisioningLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  AuthVerifyLazyRoute: AuthVerifyLazyRoute,
  RegisterConfirmationLazyRoute: RegisterConfirmationLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
