/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthenticatedSolutionsRouteImport } from './routes/_authenticated/solutions'
import { Route as AuthenticatedServiceIdentitiesRouteImport } from './routes/_authenticated/service-identities'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedProductRoleAssignmentsRouteImport } from './routes/_authenticated/product-role-assignments'
import { Route as AuthenticatedMembershipsRouteImport } from './routes/_authenticated/memberships'
import { Route as AuthenticatedBusinessObjectsRouteImport } from './routes/_authenticated/business-objects'

const InvitationsAcceptLazyRouteImport = createFileRoute(
  '/invitations/accept',
)()
const GuestRegisterLazyRouteImport = createFileRoute('/_guest/register')()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const GuestRegisterConfirmationLazyRouteImport = createFileRoute(
  '/_guest/register_/confirmation',
)()
const GuestAuthVerifyLazyRouteImport = createFileRoute('/_guest/auth/verify')()

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptLazyRoute = InvitationsAcceptLazyRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/invitations.accept.lazy').then((d) => d.Route),
)
const GuestRegisterLazyRoute = GuestRegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/register.lazy').then((d) => d.Route),
)
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
  )
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/sign-in.lazy').then((d) => d.Route),
)
const AuthenticatedSolutionsRoute = AuthenticatedSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/solutions.lazy').then((d) => d.Route),
)
const AuthenticatedServiceIdentitiesRoute =
  AuthenticatedServiceIdentitiesRouteImport.update({
    id: '/service-identities',
    path: '/service-identities',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/service-identities.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/rules.lazy').then((d) => d.Route),
)
const AuthenticatedProductRoleAssignmentsRoute =
  AuthenticatedProductRoleAssignmentsRouteImport.update({
    id: '/product-role-assignments',
    path: '/product-role-assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/product-role-assignments.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedMembershipsRoute =
  AuthenticatedMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/memberships.lazy').then((d) => d.Route),
  )
const AuthenticatedBusinessObjectsRoute =
  AuthenticatedBusinessObjectsRouteImport.update({
    id: '/business-objects',
    path: '/business-objects',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/business-objects.lazy').then(
      (d) => d.Route,
    ),
  )
const GuestRegisterConfirmationLazyRoute =
  GuestRegisterConfirmationLazyRouteImport.update({
    id: '/register_/confirmation',
    path: '/register/confirmation',
    getParentRoute: () => GuestRoute,
  } as any).lazy(() =>
    import('./routes/_guest/register_.confirmation.lazy').then((d) => d.Route),
  )
const GuestAuthVerifyLazyRoute = GuestAuthVerifyLazyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => GuestRoute,
} as any).lazy(() =>
  import('./routes/_guest/auth/verify.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-objects': typeof AuthenticatedBusinessObjectsRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/product-role-assignments': typeof AuthenticatedProductRoleAssignmentsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/service-identities': typeof AuthenticatedServiceIdentitiesRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/sign-in': typeof GuestSignInRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/register': typeof GuestRegisterLazyRoute
  '/invitations/accept': typeof InvitationsAcceptLazyRoute
  '/auth/verify': typeof GuestAuthVerifyLazyRoute
  '/register/confirmation': typeof GuestRegisterConfirmationLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-objects': typeof AuthenticatedBusinessObjectsRoute
  '/memberships': typeof AuthenticatedMembershipsRoute
  '/product-role-assignments': typeof AuthenticatedProductRoleAssignmentsRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/service-identities': typeof AuthenticatedServiceIdentitiesRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/sign-in': typeof GuestSignInRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/register': typeof GuestRegisterLazyRoute
  '/invitations/accept': typeof InvitationsAcceptLazyRoute
  '/auth/verify': typeof GuestAuthVerifyLazyRoute
  '/register/confirmation': typeof GuestRegisterConfirmationLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/business-objects': typeof AuthenticatedBusinessObjectsRoute
  '/_authenticated/memberships': typeof AuthenticatedMembershipsRoute
  '/_authenticated/product-role-assignments': typeof AuthenticatedProductRoleAssignmentsRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/service-identities': typeof AuthenticatedServiceIdentitiesRoute
  '/_authenticated/solutions': typeof AuthenticatedSolutionsRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_guest/register': typeof GuestRegisterLazyRoute
  '/invitations/accept': typeof InvitationsAcceptLazyRoute
  '/_guest/auth/verify': typeof GuestAuthVerifyLazyRoute
  '/_guest/register_/confirmation': typeof GuestRegisterConfirmationLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-objects'
    | '/memberships'
    | '/product-role-assignments'
    | '/rules'
    | '/service-identities'
    | '/solutions'
    | '/sign-in'
    | '/dashboard'
    | '/register'
    | '/invitations/accept'
    | '/auth/verify'
    | '/register/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-objects'
    | '/memberships'
    | '/product-role-assignments'
    | '/rules'
    | '/service-identities'
    | '/solutions'
    | '/sign-in'
    | '/dashboard'
    | '/register'
    | '/invitations/accept'
    | '/auth/verify'
    | '/register/confirmation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/business-objects'
    | '/_authenticated/memberships'
    | '/_authenticated/product-role-assignments'
    | '/_authenticated/rules'
    | '/_authenticated/service-identities'
    | '/_authenticated/solutions'
    | '/_guest/sign-in'
    | '/_authenticated/dashboard'
    | '/_guest/register'
    | '/invitations/accept'
    | '/_guest/auth/verify'
    | '/_guest/register_/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  InvitationsAcceptLazyRoute: typeof InvitationsAcceptLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterLazyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/solutions': {
      id: '/_authenticated/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof AuthenticatedSolutionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-identities': {
      id: '/_authenticated/service-identities'
      path: '/service-identities'
      fullPath: '/service-identities'
      preLoaderRoute: typeof AuthenticatedServiceIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/product-role-assignments': {
      id: '/_authenticated/product-role-assignments'
      path: '/product-role-assignments'
      fullPath: '/product-role-assignments'
      preLoaderRoute: typeof AuthenticatedProductRoleAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memberships': {
      id: '/_authenticated/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedMembershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/business-objects': {
      id: '/_authenticated/business-objects'
      path: '/business-objects'
      fullPath: '/business-objects'
      preLoaderRoute: typeof AuthenticatedBusinessObjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/register_/confirmation': {
      id: '/_guest/register_/confirmation'
      path: '/register/confirmation'
      fullPath: '/register/confirmation'
      preLoaderRoute: typeof GuestRegisterConfirmationLazyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/auth/verify': {
      id: '/_guest/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof GuestAuthVerifyLazyRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBusinessObjectsRoute: typeof AuthenticatedBusinessObjectsRoute
  AuthenticatedMembershipsRoute: typeof AuthenticatedMembershipsRoute
  AuthenticatedProductRoleAssignmentsRoute: typeof AuthenticatedProductRoleAssignmentsRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedServiceIdentitiesRoute: typeof AuthenticatedServiceIdentitiesRoute
  AuthenticatedSolutionsRoute: typeof AuthenticatedSolutionsRoute
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBusinessObjectsRoute: AuthenticatedBusinessObjectsRoute,
  AuthenticatedMembershipsRoute: AuthenticatedMembershipsRoute,
  AuthenticatedProductRoleAssignmentsRoute:
    AuthenticatedProductRoleAssignmentsRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedServiceIdentitiesRoute: AuthenticatedServiceIdentitiesRoute,
  AuthenticatedSolutionsRoute: AuthenticatedSolutionsRoute,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
  GuestRegisterLazyRoute: typeof GuestRegisterLazyRoute
  GuestAuthVerifyLazyRoute: typeof GuestAuthVerifyLazyRoute
  GuestRegisterConfirmationLazyRoute: typeof GuestRegisterConfirmationLazyRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
  GuestRegisterLazyRoute: GuestRegisterLazyRoute,
  GuestAuthVerifyLazyRoute: GuestAuthVerifyLazyRoute,
  GuestRegisterConfirmationLazyRoute: GuestRegisterConfirmationLazyRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  InvitationsAcceptLazyRoute: InvitationsAcceptLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
