// <auto-generated />
// Generated from theme/axis-theme.json by `python scripts/axis.py generate theme`.

export const axisUiTiming = {
  feedback: {
    delayMs: 300,
    minimumMs: 400,
  },
  contextTransition: {
    delayMs: 500,
    minimumMs: 600,
  },
} as const;
