<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axis.Data\Axis.Data.csproj" />
    <ProjectReference Include="..\Axis.Tenancy\Axis.Tenancy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Axis.Server.Tests" />
    <InternalsVisibleTo Include="Axis.Integration.Tests" />
  </ItemGroup>

</Project>
