// <auto-generated />
// Generated from theme/axis-theme.json by `python scripts/axis.py generate theme`.

namespace Axis.Identity.Infrastructure.Services;

internal static class TransactionalEmailTheme
{
    internal const string BackgroundColor = "#faf7f1";
    internal const string CardColor = "#fefdfb";
    internal const string ForegroundColor = "#1a1a23";
    internal const string MutedColor = "#5c5c6b";
    internal const string BorderColor = "#d0d0da";
    internal const string PrimaryColor = "#633767";
    internal const string PrimaryForegroundColor = "#fbfaf7";
    internal const string LinkColor = "#633767";
    internal const string AccentColor = "#eeebe4";
    internal const string WarningBackgroundColor = "#f3ede2";
    internal const string WarningBorderColor = "#e3d5bc";
    internal const string WarningTextColor = "#905d00";
    internal const string FontFamily = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,Helvetica,sans-serif";
}
