/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/business-object-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List business object definitions for the current workspace */
        get: operations["ListBusinessObjectDefinitions"];
        put?: never;
        /** Create an unpublished business object definition */
        post: operations["CreateBusinessObjectDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-object-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a business object definition */
        get: operations["GetBusinessObjectDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-object-definitions/{id}/unpublished": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save an unpublished business object definition */
        put: operations["SaveUnpublishedBusinessObjectDefinition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-object-definitions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an unpublished business object definition */
        post: operations["PublishBusinessObjectDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Terms of Service and Privacy Policy versions */
        get: operations["GetLegalVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in a standalone user account */
        post: operations["SignInUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an email token and establish the registration session */
        post: operations["VerifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend email verification link */
        post: operations["ResendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out the current browser session */
        post: operations["SignOutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a standalone user account */
        post: operations["RegisterUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile */
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/preferences/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the current user's language preference */
        put: operations["UpdateLanguagePreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/preferences/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the current user's theme preference */
        put: operations["UpdateThemePreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List system and workspace rule definitions */
        get: operations["ListRuleDefinitions"];
        put?: never;
        /** Create a workspace rule draft */
        post: operations["CreateRuleDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/context-schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rule context schemas available to the workspace */
        get: operations["ListRuleContextSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{definitionKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a workspace rule definition and its versions */
        get: operations["GetRuleDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{definitionKey}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save a workspace rule draft */
        put: operations["SaveRuleDefinitionDraft"];
        /** Start the next draft from a published workspace rule */
        post: operations["StartRuleDefinitionDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{definitionKey}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an immutable workspace rule version */
        post: operations["PublishRuleDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{definitionKey}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a workspace rule definition */
        post: operations["ArchiveRuleDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{definitionKey}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a workspace rule draft or exact published version */
        post: operations["SimulateRuleDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BusinessObjectChoiceFieldConfigurationDto: {
            selectionMode?: components["schemas"]["BusinessObjectChoiceSelectionMode"];
            options?: components["schemas"]["BusinessObjectChoiceOptionDto"][];
        };
        BusinessObjectChoiceFieldConfigurationInput: {
            selectionMode?: components["schemas"]["BusinessObjectChoiceSelectionMode"];
            options?: components["schemas"]["BusinessObjectChoiceOptionInput"][];
        };
        BusinessObjectChoiceOptionDto: {
            /** Format: uuid */
            id?: string;
            optionKey?: string;
            label?: string;
            /** Format: int32 */
            order?: number;
        };
        BusinessObjectChoiceOptionInput: {
            optionKey?: string;
            label?: string;
            /** Format: uuid */
            id?: string | null;
        };
        /** @enum {string} */
        BusinessObjectChoiceSelectionMode: "Single" | "Multiple";
        BusinessObjectDefinitionDetailDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspaceId?: string;
            name?: string;
            objectKey?: string;
            status?: components["schemas"]["BusinessObjectDefinitionStatus"];
            /** Format: int32 */
            revision?: number;
            /** Format: int32 */
            latestPublishedVersionNumber?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            fields?: components["schemas"]["BusinessObjectFieldDefinitionDto"][];
            latestPublishedVersion?: components["schemas"]["BusinessObjectDefinitionVersionDto"];
        };
        BusinessObjectDefinitionListItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            objectKey?: string;
            status?: components["schemas"]["BusinessObjectDefinitionStatus"];
            /** Format: int32 */
            revision?: number;
            /** Format: int32 */
            latestPublishedVersionNumber?: number | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        BusinessObjectDefinitionListItemDtoPagedResult: {
            items?: components["schemas"]["BusinessObjectDefinitionListItemDto"][];
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        /** @enum {string} */
        BusinessObjectDefinitionStatus: "Unpublished" | "Published";
        BusinessObjectDefinitionVersionChoiceFieldConfigurationDto: {
            selectionMode?: components["schemas"]["BusinessObjectChoiceSelectionMode"];
            options?: components["schemas"]["BusinessObjectDefinitionVersionChoiceOptionDto"][];
        };
        BusinessObjectDefinitionVersionChoiceOptionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sourceChoiceOptionId?: string;
            optionKey?: string;
            label?: string;
            /** Format: int32 */
            order?: number;
        };
        BusinessObjectDefinitionVersionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sourceDefinitionId?: string;
            /** Format: int32 */
            versionNumber?: number;
            /** Format: uuid */
            publishedByUserId?: string;
            /** Format: date-time */
            publishedAt?: string;
            fields?: components["schemas"]["BusinessObjectDefinitionVersionFieldDto"][];
        };
        BusinessObjectDefinitionVersionFieldDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sourceFieldDefinitionId?: string;
            fieldKey?: string;
            label?: string;
            /** Format: int32 */
            order?: number;
            fieldType?: components["schemas"]["BusinessObjectFieldType"];
            choiceConfiguration?: components["schemas"]["BusinessObjectDefinitionVersionChoiceFieldConfigurationDto"];
            rules?: components["schemas"]["BusinessObjectDefinitionVersionFieldRuleDto"][];
        };
        BusinessObjectDefinitionVersionFieldRuleDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sourceFieldRuleId?: string;
            definitionKey?: string;
            /** Format: int32 */
            definitionVersion?: number;
            parameters?: {
                [key: string]: string[];
            };
        };
        BusinessObjectFieldDefinitionDto: {
            /** Format: uuid */
            id?: string;
            fieldKey?: string;
            label?: string;
            /** Format: int32 */
            order?: number;
            fieldType?: components["schemas"]["BusinessObjectFieldType"];
            choiceConfiguration?: components["schemas"]["BusinessObjectChoiceFieldConfigurationDto"];
            rules?: components["schemas"]["BusinessObjectFieldRuleDto"][];
        };
        BusinessObjectFieldDefinitionInput: {
            fieldKey?: string;
            label?: string;
            fieldType?: components["schemas"]["BusinessObjectFieldType"];
            rules?: components["schemas"]["BusinessObjectFieldRuleInput"][] | null;
            choiceConfiguration?: components["schemas"]["BusinessObjectChoiceFieldConfigurationInput"];
            /** Format: uuid */
            id?: string | null;
        };
        BusinessObjectFieldRuleDto: {
            /** Format: uuid */
            id?: string;
            definitionKey?: string;
            /** Format: int32 */
            definitionVersion?: number;
            parameters?: {
                [key: string]: string[];
            };
        };
        BusinessObjectFieldRuleInput: {
            definitionKey?: string;
            /** Format: int32 */
            definitionVersion?: number;
            parameters?: {
                [key: string]: string[];
            } | null;
            /** Format: uuid */
            id?: string | null;
        };
        /** @enum {string} */
        BusinessObjectFieldType: "Text" | "Integer" | "Decimal" | "Date" | "DateTime" | "Boolean" | "Choice";
        CreateBusinessObjectDefinitionRequest: {
            name?: string;
        };
        CreateRuleDefinitionRequest: {
            name?: string;
            description?: string;
            scope?: components["schemas"]["RuleScope"];
            contextKey?: string;
            /** Format: int32 */
            contextSchemaVersion?: number;
            outcomeKind?: components["schemas"]["RuleOutcomeKind"];
        };
        CurrentUserProfileDto: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            isActive?: boolean;
            language?: string | null;
            theme?: string | null;
            /** Format: uuid */
            workspaceId?: string | null;
            workspaces?: components["schemas"]["UserWorkspaceDto"][];
        };
        LanguagePreferenceDto: {
            language?: string;
        };
        LegalVersionsDto: {
            termsVersion?: string;
            privacyVersion?: string;
        };
        MessageResponse: {
            message?: string;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description Stable machine-readable problem code for client behavior and localization. */
            code?: string | null;
            /** @description Optional field-level machine-readable validation codes keyed by JSON field name. */
            errorCodes?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        PublishBusinessObjectDefinitionRequest: {
            /** Format: int32 */
            expectedRevision?: number;
        };
        RegisterUserRequest: {
            fullName?: string;
            email?: string;
            password?: string;
            passwordConfirmation?: string;
            acceptedTermsVersion?: string;
            acceptedPrivacyVersion?: string;
            preferredLanguage?: string | null;
        };
        ResendVerificationRequest: {
            email?: string;
        };
        RuleApplicabilityDto: {
            targetTypeKeys?: string[];
            configurationConstraints?: {
                [key: string]: string[];
            };
        };
        RuleConditionNodeDto: {
            nodeId?: string;
            logicalOperator?: components["schemas"]["RuleLogicalOperator"];
            predicateOperator?: components["schemas"]["RulePredicateOperator"];
            left?: components["schemas"]["RuleOperandDto"];
            right?: components["schemas"]["RuleOperandDto"];
            children?: components["schemas"]["RuleConditionNodeDto"][];
        };
        RuleContextFieldDto: {
            path?: string;
            displayName?: string;
            type?: components["schemas"]["RuleValueType"];
            allowMultiple?: boolean;
        };
        RuleContextSchemaDto: {
            contextKey?: string;
            /** Format: int32 */
            version?: number;
            scope?: components["schemas"]["RuleScope"];
            displayName?: string;
            fields?: components["schemas"]["RuleContextFieldDto"][];
            targetTypeKey?: string | null;
            configuration?: {
                [key: string]: string[];
            } | null;
        };
        /** @enum {string} */
        RuleDecision: "Allow" | "Deny";
        RuleDefinitionDetailDto: {
            definitionKey?: string;
            name?: string;
            description?: string;
            origin?: components["schemas"]["RuleOrigin"];
            scope?: components["schemas"]["RuleScope"];
            outcomeKind?: components["schemas"]["RuleOutcomeKind"];
            status?: components["schemas"]["RuleLifecycleStatus"];
            /** Format: int32 */
            revision?: number;
            /** Format: int32 */
            latestPublishedVersion?: number | null;
            contextKey?: string;
            /** Format: int32 */
            contextSchemaVersion?: number;
            parameters?: components["schemas"]["RuleParameterDefinitionDto"][];
            condition?: components["schemas"]["RuleConditionNodeDto"];
            outcome?: components["schemas"]["RuleOutcomeDto"];
            versions?: components["schemas"]["RuleDefinitionVersionDto"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            archivedAt?: string | null;
        };
        RuleDefinitionSummaryDto: {
            definitionKey?: string;
            name?: string;
            description?: string;
            origin?: components["schemas"]["RuleOrigin"];
            scope?: components["schemas"]["RuleScope"];
            outcomeKind?: components["schemas"]["RuleOutcomeKind"];
            status?: components["schemas"]["RuleLifecycleStatus"];
            /** Format: int32 */
            revision?: number | null;
            /** Format: int32 */
            latestPublishedVersion?: number | null;
            contextKey?: string | null;
            /** Format: int32 */
            contextSchemaVersion?: number | null;
            applicability?: components["schemas"]["RuleApplicabilityDto"];
            parameters?: components["schemas"]["RuleParameterDefinitionDto"][];
            /** Format: date-time */
            updatedAt?: string | null;
        };
        RuleDefinitionSummaryDtoPagedResult: {
            items?: components["schemas"]["RuleDefinitionSummaryDto"][];
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        RuleDefinitionVersionDto: {
            /** Format: int32 */
            version?: number;
            name?: string;
            description?: string;
            scope?: components["schemas"]["RuleScope"];
            outcomeKind?: components["schemas"]["RuleOutcomeKind"];
            contextKey?: string;
            /** Format: int32 */
            contextSchemaVersion?: number;
            parameters?: components["schemas"]["RuleParameterDefinitionDto"][];
            condition?: components["schemas"]["RuleConditionNodeDto"];
            outcome?: components["schemas"]["RuleOutcomeDto"];
            /** Format: uuid */
            publishedByUserId?: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        /** @enum {string} */
        RuleLifecycleStatus: "Draft" | "Published" | "Archived";
        /** @enum {string} */
        RuleLogicalOperator: "All" | "Any" | "Not";
        RuleNodeDiagnosticDto: {
            nodeId?: string;
            isMatch?: boolean;
        };
        RuleOperandDto: {
            kind?: components["schemas"]["RuleOperandKind"];
            reference?: string | null;
            literal?: components["schemas"]["RuleValueDto"];
        };
        /** @enum {string} */
        RuleOperandKind: "Context" | "Parameter" | "Literal";
        /** @enum {string} */
        RuleOrigin: "System" | "Workspace";
        RuleOutcomeDto: {
            kind?: components["schemas"]["RuleOutcomeKind"];
            violationCode?: string | null;
            severity?: components["schemas"]["RuleSeverity"];
            message?: string | null;
            decision?: components["schemas"]["RuleDecision"];
        };
        /** @enum {string} */
        RuleOutcomeKind: "Validation" | "Decision";
        RuleParameterDefinitionDto: {
            key?: string;
            type?: components["schemas"]["RuleValueType"];
            isRequired?: boolean;
            allowMultiple?: boolean;
            allowedValues?: string[];
        };
        /** @enum {string} */
        RulePredicateOperator: "Equal" | "NotEqual" | "GreaterThan" | "GreaterThanOrEqual" | "LessThan" | "LessThanOrEqual" | "Contains" | "StartsWith" | "EndsWith" | "IsNull" | "IsNotNull";
        RuleRevisionRequest: {
            /** Format: int32 */
            expectedRevision?: number;
        };
        /** @enum {string} */
        RuleScope: "Field" | "Object" | "Record" | "Lifecycle";
        /** @enum {string} */
        RuleSeverity: "Info" | "Warning" | "Error";
        RuleSimulationResultDto: {
            definitionKey?: string;
            /** Format: int32 */
            definitionVersion?: number | null;
            isMatch?: boolean;
            outcome?: components["schemas"]["RuleOutcomeDto"];
            diagnostics?: components["schemas"]["RuleNodeDiagnosticDto"][];
            correlationId?: string;
        };
        RuleValueDto: {
            type?: components["schemas"]["RuleValueType"];
            values?: string[];
        };
        /** @enum {string} */
        RuleValueType: "Text" | "Integer" | "Decimal" | "Date" | "DateTime" | "Boolean";
        SaveRuleDefinitionDraftRequest: {
            /** Format: int32 */
            expectedRevision?: number;
            name?: string;
            description?: string;
            scope?: components["schemas"]["RuleScope"];
            contextKey?: string;
            /** Format: int32 */
            contextSchemaVersion?: number;
            outcomeKind?: components["schemas"]["RuleOutcomeKind"];
            parameters?: components["schemas"]["RuleParameterDefinitionDto"][];
            condition?: components["schemas"]["RuleConditionNodeDto"];
            outcome?: components["schemas"]["RuleOutcomeDto"];
        };
        SaveUnpublishedBusinessObjectDefinitionRequest: {
            /** Format: int32 */
            expectedRevision?: number;
            name?: string;
            fields?: components["schemas"]["BusinessObjectFieldDefinitionInput"][];
        };
        /** @enum {string} */
        SignInNextStep: "Dashboard";
        SignInSessionEstablishedDto: {
            sessionEstablished?: boolean;
            nextStep?: components["schemas"]["SignInNextStep"];
        };
        SignInUserRequest: {
            email?: string;
            password?: string;
        };
        SimulateRuleRequest: {
            /** Format: int32 */
            definitionVersion?: number | null;
            parameters?: {
                [key: string]: components["schemas"]["RuleValueDto"];
            };
            context?: {
                [key: string]: components["schemas"]["RuleValueDto"];
            };
            correlationId?: string;
        };
        ThemePreferenceDto: {
            theme?: string;
        };
        UpdateUserLanguagePreferenceRequest: {
            language?: string;
        };
        UpdateUserThemePreferenceRequest: {
            theme?: string;
        };
        UserWorkspaceDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            type?: string;
            isCurrent?: boolean;
        };
        /** @enum {string} */
        VerifyEmailNextStep: "Dashboard";
        VerifyEmailRequest: {
            token?: string;
        };
        VerifyEmailSessionEstablishedDto: {
            sessionEstablished?: boolean;
            nextStep?: components["schemas"]["VerifyEmailNextStep"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListBusinessObjectDefinitions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessObjectDefinitionListItemDtoPagedResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateBusinessObjectDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusinessObjectDefinitionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessObjectDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBusinessObjectDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessObjectDefinitionDetailDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SaveUnpublishedBusinessObjectDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveUnpublishedBusinessObjectDefinitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessObjectDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PublishBusinessObjectDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishBusinessObjectDefinitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessObjectDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLegalVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalVersionsDto"];
                };
            };
        };
    };
    SignInUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInSessionEstablishedDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    VerifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailSessionEstablishedDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ResendEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SignOutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegisterUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserProfileDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateLanguagePreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserLanguagePreferenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguagePreferenceDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateThemePreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserThemePreferenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemePreferenceDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListRuleDefinitions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                scope?: components["schemas"]["RuleScope"];
                origin?: components["schemas"]["RuleOrigin"];
                status?: components["schemas"]["RuleLifecycleStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionSummaryDtoPagedResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateRuleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleDefinitionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListRuleContextSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleContextSchemaDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRuleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SaveRuleDefinitionDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRuleDefinitionDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StartRuleDefinitionDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRevisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PublishRuleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRevisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ArchiveRuleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRevisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDefinitionDetailDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SimulateRuleDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definitionKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSimulationResultDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
