// <auto-generated />
using System;
using Axis.Processes.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axis.Processes.Storage.Migrations
{
    [DbContext(typeof(ProcessesDbContext))]
    [Migration("20261010121625_CreateProcessInstances")]
    partial class CreateProcessInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("axis")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axis.Processes.Storage.ProcessInstanceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step");

                    b.Property<Guid>("SubjectEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_entity_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_process_instances");

                    b.HasIndex("ApplicationId", "ProcessId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_process_instances_active_subject")
                        .HasFilter("state IN ('running', 'waiting')");

                    b.ToTable("process_instances", "axis");
                });

            modelBuilder.Entity("Axis.Processes.Storage.ProcessStartReceiptRow", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("ApplicationId", "ProcessId", "Key")
                        .HasName("pk_process_start_receipts");

                    b.ToTable("process_start_receipts", "axis");
                });

            modelBuilder.Entity("Axis.Processes.Storage.WorkItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("ProcessInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_instance_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_process_work_items");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_process_work_items_due_at");

                    b.HasIndex("ProcessInstanceId")
                        .HasDatabaseName("ix_process_work_items_process_instance_id");

                    b.ToTable("process_work_items", "axis");
                });

            modelBuilder.Entity("Axis.Processes.Storage.WorkItemRow", b =>
                {
                    b.HasOne("Axis.Processes.Storage.ProcessInstanceRow", null)
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_process_work_items_process_instances_process_instance_id");
                });
#pragma warning restore 612, 618
        }
    }
}
